use_frameworks!

target 'HoneyRefresh_Example' do
  pod 'HoneyRefresh', :path => '../'

  target 'HoneyRefresh_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
